### PR TITLE
move to local fonts b/c the alternative is dumb

### LINKED ISSUE #61: Fonts intermittently don't load in development environment
Sometimes when running `yarn dev`, the console throws up the following errors
```
FetchError: request to https://fonts.googleapis.com/css2?family=Rubik:wght@300..900&display=swap failed, reason: 
    at ClientRequest.<anonymous> (/home/joshua/Documents/Programming/frontend/node_modules/next/dist/compiled/node-fetch/index.js:1:65756)
    at ClientRequest.emit (node:events:511:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:511:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7) {
  type: 'system',
  errno: 'ENETUNREACH',
  code: 'ENETUNREACH'
}
- error Failed to download `Rubik` from Google Fonts. Using fallback font instead.
FetchError: request to https://fonts.googleapis.com/css2?family=Orbitron:wght@400..900&display=swap failed, reason: 
    at ClientRequest.<anonymous> (/home/joshua/Documents/Programming/frontend/node_modules/next/dist/compiled/node-fetch/index.js:1:65756)
    at ClientRequest.emit (node:events:511:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:511:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processTimers (node:internal/timers:511:9) {
  type: 'system',
  errno: 'ENETUNREACH',
  code: 'ENETUNREACH'
}
- error Failed to download `Orbitron` from Google Fonts. Using fallback font instead.
```

The result of this is that the site resorts to using the default `serif` font, as shown
image

Apart from the fact that the fonts don't load, we ought to also ensure that the fallback font is a sans serif font as opposed to a serif one.

### PR DESCRIPTION
**Pull request by aslink87**
fixes #61 

We were using next/fonts and users were sometimes unable to download the fonts causing fallbacks to render.
Here I've moved to only local fonts for the project.

This involved:

- refactoring route headings to use a custom `<PageHeading>` component that applies a local heading font
- defaulted the entire app to a local body font
- had to update the side nav drawer a bit to allow for the <PageHeading> component
- Chakra is failing to apply custom fonts in its `extendTheme` function. If that wasn't the case we could have defined the heading and body fonts there instead of injecting them in a custom `<PageHeader>` component, or importing them within the app.

### CODE REVIEW

File: app/_lib/moduleProps.tsx [hunk 1]
```diff
@@ -21,75 +21,75 @@ export interface Module {
   description: string;
 }
 
-export const Tags = ['discover', 'trade', 'outfit'];
+export const Tags = ['Discover', 'Trade', 'Outfit'];
```
Comment (chrismou) [inline app/_lib/moduleProps.tsx:24]: @aslink87 Whats happening here, I can't work out what this change is doing. Looks to be a bunch of case changes, then later you're just converting them back to lower case for comparison?

File: app/_lib/moduleProps.tsx [hunk 2]
```diff
@@ -105,7 +105,7 @@ const ModuleProps: Module[] = [
   },
```
Comment (chrismou) [inline app/_lib/moduleProps.tsx:105]: You've missed multi, its disappeared out the nav menu. Probably worth adding a basic test for this at some point but maybe outside the scope of this PR

**Review by chrismou — CHANGES_REQUESTED** [review]

File: app/_lib/moduleProps.tsx (hunk 1 above)
Comment (aslink87) [reply app/_lib/moduleProps.tsx:24]: I needed to make the tags in the desired case because they were no longer having their case changed in the component, so they rendered in lower. I've removed the lower case comparison check.

File: app/_lib/moduleProps.tsx (hunk 2 above)
Comment (aslink87) [reply app/_lib/moduleProps.tsx:105]: Fixed, thanks

**Review by chrismou — APPROVED** [review]

**Review by nitishdhar — APPROVED** [review]
