### PR TITLE
68 fix navbar

### LINKED ISSUE #68: Make Nav Drawer logo and heading size proportional to Navbar
The nav drawer logo and other headings are slightly bigger than the main navbar content

### PR DESCRIPTION
**Pull request by SharmaTushar1**
Closes #68 #80 

image

### CODE REVIEW

File: app/_components/nav-drawer/NavDrawer.tsx [hunk 1]
```diff
@@ -59,13 +59,13 @@ const NavDrawer = () => {
                 <Image
                   src={'/EDPN_logo_dark_background.png'}
```
Comment (jbritain) [inline app/_components/nav-drawer/NavDrawer.tsx]: Considering the dimensions of the header, instead of the EDPN text, really we should have the full project name. The spelled version of the logo is ideal for this, and I have made a version without the background for this purpose.
EDPN_logo_spelled_transparent

**Review by jbritain — CHANGES_REQUESTED** [review]

File: app/_components/nav-drawer/NavDrawer.tsx (hunk 1 above)
Comment (SharmaTushar1) [reply app/_components/nav-drawer/NavDrawer.tsx]: image

**Review by jbritain — APPROVED** [review]
